<a href="https://colab.research.google.com/github/953625244013-cell/RFM-CLV-Personalized-Email/blob/main/AI_Powered_Customer_Segmentation_and_Personalized_Email_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# Segment-specific email prompts

segment_prompts = {
    "Champions":
        "Thank the loyal customer and provide an exclusive reward.",

    "Loyal Customers":
        "Appreciate their continued purchases and encourage repeat purchases.",

    "Potential Loyalists":
        "Encourage the customer to become a regular customer with an attractive offer.",

    "At Risk":
        "Encourage the customer to return by highlighting a special offer.",

    "Lost Customers":
        "Try to win back the customer with a strong promotional offer.",

    "Others":
        "Create a simple promotional message to increase customer engagement."
}

print(segment_prompts)

{'Champions': 'Thank the loyal customer and provide an exclusive reward.', 'Loyal Customers': 'Appreciate their continued purchases and encourage repeat purchases.', 'Potential Loyalists': 'Encourage the customer to become a regular customer with an attractive offer.', 'At Risk': 'Encourage the customer to return by highlighting a special offer.', 'Lost Customers': 'Try to win back the customer with a strong promotional offer.', 'Others': 'Create a simple promotional message to increase customer engagement.'}

In [27]:
# Create prompt for each customer segment

def create_segment_prompt(customer_name, segment, offer):

    guideline = segment_prompts.get(
        segment,
        "Create a friendly promotional message."
    )

    return f"""
Create a short personalized marketing email.

Customer: {customer_name}
Segment: {segment}
Offer: {offer}

Communication guideline:
{guideline}

Requirements:
- Use a friendly and professional tone.
- Keep the email short and clear.
- Mention the offer.
- Include a call-to-action.
- End with "Best Regards, Customer Success Team".
"""

In [28]:
# Test segment-specific prompt

customer_name = "Dharshini"
segment = "Champions"
offer = "20% OFF"

prompt = create_segment_prompt(
    customer_name,
    segment,
    offer
)

print(prompt)

Create a short personalized marketing email.

Customer: Dharshini
Segment: Champions
Offer: 20% OFF

Communication guideline:
Thank the loyal customer and provide an exclusive reward.

Requirements:
- Use a friendly and professional tone.
- Keep the email short and clear.
- Mention the offer.
- Include a call-to-action.
- End with "Best Regards, Customer Success Team".

In [29]:
# Generate prompts for all customer segments

segment_prompts = {
    "Champions": "Thank the loyal customer and provide an exclusive reward.",
    "Loyal Customers": "Appreciate their continued purchases and encourage repeat purchases.",
    "Potential Loyalists": "Encourage the customer to become a regular customer.",
    "At Risk": "Encourage the customer to return with a special offer.",
    "Lost Customers": "Try to win back the customer with a promotional offer.",
    "Others": "Create a simple promotional message to increase engagement."
}

segment_offers = {
    "Champions": "20% OFF",
    "Loyal Customers": "15% OFF",
    "Potential Loyalists": "10% OFF",
    "At Risk": "25% OFF",
    "Lost Customers": "30% OFF",
    "Others": "10% OFF"
}

for segment in segment_prompts:
    offer = segment_offers[segment]
    guideline = segment_prompts[segment]

    prompt = f"""
Create a short personalized marketing email.

Customer: Customer
Segment: {segment}
Offer: {offer}

Guideline:
{guideline}

Use a friendly and professional tone.
Mention the offer clearly.
Include a call-to-action.
End with:
Best Regards,
Customer Success Team
"""

    print("=" * 60)
    print("SEGMENT:", segment)
    print(prompt)

============================================================
SEGMENT: Champions

Create a short personalized marketing email.

Customer: Customer
Segment: Champions
Offer: 20% OFF

Guideline:
Thank the loyal customer and provide an exclusive reward.

Use a friendly and professional tone.
Mention the offer clearly.
Include a call-to-action.
End with:
Best Regards,
Customer Success Team

============================================================
SEGMENT: Loyal Customers

Create a short personalized marketing email.

Customer: Customer
Segment: Loyal Customers
Offer: 15% OFF

Guideline:
Appreciate their continued purchases and encourage repeat purchases.

Use a friendly and professional tone.
Mention the offer clearly.
Include a call-to-action.
End with:
Best Regards,
Customer Success Team

============================================================
SEGMENT: Potential Loyalists

Create a short personalized marketing email.

Customer: Customer
Segment: Potential Loyalists
Offer: 10% OFF

Guideline:
Encourage the customer to become a regular customer.

Use a friendly and professional tone.
Mention the offer clearly.
Include a call-to-action.
End with:
Best Regards,
Customer Success Team

============================================================
SEGMENT: At Risk

Create a short personalized marketing email.

Customer: Customer
Segment: At Risk
Offer: 25% OFF

Guideline:
Encourage the customer to return with a special offer.

Use a friendly and professional tone.
Mention the offer clearly.
Include a call-to-action.
End with:
Best Regards,
Customer Success Team

============================================================
SEGMENT: Lost Customers

Create a short personalized marketing email.

Customer: Customer
Segment: Lost Customers
Offer: 30% OFF

Guideline:
Try to win back the customer with a promotional offer.

Use a friendly and professional tone.
Mention the offer clearly.
Include a call-to-action.
End with:
Best Regards,
Customer Success Team

============================================================
SEGMENT: Others

Create a short personalized marketing email.

Customer: Customer
Segment: Others
Offer: 10% OFF

Guideline:
Create a simple promotional message to increase engagement.

Use a friendly and professional tone.
Mention the offer clearly.
Include a call-to-action.
End with:
Best Regards,
Customer Success Team

In [30]:
# Generate personalized emails using segment-specific prompts

import pandas as pd

customers = [
    {"Name": "Arun", "Segment": "Champions"},
    {"Name": "Priya", "Segment": "Loyal Customers"},
    {"Name": "Kavi", "Segment": "Potential Loyalists"},
    {"Name": "Dharshini", "Segment": "At Risk"},
    {"Name": "Nithya", "Segment": "Lost Customers"}
]

segment_offers = {
    "Champions": "20% OFF",
    "Loyal Customers": "15% OFF",
    "Potential Loyalists": "10% OFF",
    "At Risk": "25% OFF",
    "Lost Customers": "30% OFF",
    "Others": "10% OFF"
}

segment_prompts = {
    "Champions": "Thank the loyal customer and provide an exclusive reward.",
    "Loyal Customers": "Appreciate their continued purchases and encourage repeat purchases.",
    "Potential Loyalists": "Encourage the customer to become a regular customer.",
    "At Risk": "Encourage the customer to return with a special offer.",
    "Lost Customers": "Try to win back the customer with a promotional offer."
}

segment_emails = []

for customer in customers:

    name = customer["Name"]
    segment = customer["Segment"]

    offer = segment_offers.get(segment, "10% OFF")

    guideline = segment_prompts.get(
        segment,
        "Create a friendly promotional message."
    )

    email = f"""
Hi {name},

Thank you for being a valued customer!

As a {segment}, we have a special offer for you:
{offer}

{guideline}

Don't miss this special opportunity. We look forward to serving you again!

Best Regards,
Customer Success Team
"""

    segment_emails.append({
        "Customer": name,
        "Segment": segment,
        "Offer": offer,
        "Email": email
    })

segment_email_df = pd.DataFrame(segment_emails)

display(segment_email_df)

,Customer,Segment,Offer,Email
0,Arun,Champions,20% OFF,"\nHi Arun,\n\nThank you for being a valued cus..."
1,Priya,Loyal Customers,15% OFF,"\nHi Priya,\n\nThank you for being a valued cu..."
2,Kavi,Potential Loyalists,10% OFF,"\nHi Kavi,\n\nThank you for being a valued cus..."
3,Dharshini,At Risk,25% OFF,"\nHi Dharshini,\n\nThank you for being a value..."
4,Nithya,Lost Customers,30% OFF,"\nHi Nithya,\n\nThank you for being a valued c..."

In [31]:
# Preview segment-specific emails

for _, row in segment_email_df.iterrows():
    print("=" * 60)
    print("Customer :", row["Customer"])
    print("Segment  :", row["Segment"])
    print("Offer    :", row["Offer"])
    print("\nEmail:")
    print(row["Email"])

============================================================
Customer : Arun
Segment  : Champions
Offer    : 20% OFF

Email:

Hi Arun,

Thank you for being a valued customer!

As a Champions, we have a special offer for you:
20% OFF

Thank the loyal customer and provide an exclusive reward.

Don't miss this special opportunity. We look forward to serving you again!

Best Regards,
Customer Success Team

============================================================
Customer : Priya
Segment  : Loyal Customers
Offer    : 15% OFF

Email:

Hi Priya,

Thank you for being a valued customer!

As a Loyal Customers, we have a special offer for you:
15% OFF

Appreciate their continued purchases and encourage repeat purchases.

Don't miss this special opportunity. We look forward to serving you again!

Best Regards,
Customer Success Team

============================================================
Customer : Kavi
Segment  : Potential Loyalists
Offer    : 10% OFF

Email:

Hi Kavi,

Thank you for being a valued customer!

As a Potential Loyalists, we have a special offer for you:
10% OFF

Encourage the customer to become a regular customer.

Don't miss this special opportunity. We look forward to serving you again!

Best Regards,
Customer Success Team

============================================================
Customer : Dharshini
Segment  : At Risk
Offer    : 25% OFF

Email:

Hi Dharshini,

Thank you for being a valued customer!

As a At Risk, we have a special offer for you:
25% OFF

Encourage the customer to return with a special offer.

Don't miss this special opportunity. We look forward to serving you again!

Best Regards,
Customer Success Team

============================================================
Customer : Nithya
Segment  : Lost Customers
Offer    : 30% OFF

Email:

Hi Nithya,

Thank you for being a valued customer!

As a Lost Customers, we have a special offer for you:
30% OFF

Try to win back the customer with a promotional offer.

Don't miss this special opportunity. We look forward to serving you again!

Best Regards,
Customer Success Team

In [32]:
# Validate segment-specific emails

def check_email(email):
    return (
        len(str(email)) > 20
        and "offer" in str(email).lower()
        and "best regards" in str(email).lower()
    )

segment_email_df["Valid"] = segment_email_df["Email"].apply(check_email)

print("Email Validation Results:")
display(segment_email_df[[
    "Customer",
    "Segment",
    "Offer",
    "Valid"
]])

Email Validation Results:

    Customer              Segment    Offer  Valid
0       Arun            Champions  20% OFF   True
1      Priya      Loyal Customers  15% OFF   True
2       Kavi  Potential Loyalists  10% OFF   True
3  Dharshini              At Risk  25% OFF   True
4     Nithya       Lost Customers  30% OFF   True

In [33]:
# Segment-wise email summary

summary = (
    segment_email_df
    .groupby("Segment")
    .agg(
        Customers=("Customer", "count"),
        Valid_Emails=("Valid", "sum")
    )
    .reset_index()
)

display(summary)

               Segment  Customers  Valid_Emails
0              At Risk          1             1
1            Champions          1             1
2       Lost Customers          1             1
3      Loyal Customers          1             1
4  Potential Loyalists          1             1

In [34]:
# Final segment-specific prompt report

for segment in segment_prompts:
    print("=" * 50)
    print("SEGMENT :", segment)
    print("GUIDELINE:", segment_prompts[segment])
    print("OFFER    :", segment_offers.get(segment, "10% OFF"))

print("\nSegment-specific prompt design completed successfully!")

==================================================
SEGMENT : Champions
GUIDELINE: Thank the loyal customer and provide an exclusive reward.
OFFER    : 20% OFF
==================================================
SEGMENT : Loyal Customers
GUIDELINE: Appreciate their continued purchases and encourage repeat purchases.
OFFER    : 15% OFF
==================================================
SEGMENT : Potential Loyalists
GUIDELINE: Encourage the customer to become a regular customer.
OFFER    : 10% OFF
==================================================
SEGMENT : At Risk
GUIDELINE: Encourage the customer to return with a special offer.
OFFER    : 25% OFF
==================================================
SEGMENT : Lost Customers
GUIDELINE: Try to win back the customer with a promotional offer.
OFFER    : 30% OFF

Segment-specific prompt design completed successfully!

In [35]:
# Final segment-specific email report

final_segment_report = segment_email_df[
    ["Customer", "Segment", "Offer", "Email", "Valid"]
]

display(final_segment_report)

print("Final segment-specific email report generated successfully!")

,Customer,Segment,Offer,Email,Valid
0,Arun,Champions,20% OFF,"\nHi Arun,\n\nThank you for being a valued cus...",True
1,Priya,Loyal Customers,15% OFF,"\nHi Priya,\n\nThank you for being a valued cu...",True
2,Kavi,Potential Loyalists,10% OFF,"\nHi Kavi,\n\nThank you for being a valued cus...",True
3,Dharshini,At Risk,25% OFF,"\nHi Dharshini,\n\nThank you for being a value...",True
4,Nithya,Lost Customers,30% OFF,"\nHi Nithya,\n\nThank you for being a valued c...",True

Final segment-specific email report generated successfully!

In [36]:
# Save final segment-specific email report

final_segment_report.to_csv(
    "Final_Segment_Specific_Email_Report.csv",
    index=False
)

print("Final segment-specific email report saved successfully!")

Final segment-specific email report saved successfully!

In [37]:
# Final Summary

print("=" * 55)
print("SEGMENT-SPECIFIC EMAIL GENERATION")
print("=" * 55)

print("Total Customers :", len(segment_email_df))
print("Total Segments  :", segment_email_df["Segment"].nunique())
print("Valid Emails    :", segment_email_df["Valid"].sum())

print("\nSegments:")
for segment in segment_email_df["Segment"].unique():
    print("-", segment)

print("\nStatus: COMPLETED")

=======================================================
SEGMENT-SPECIFIC EMAIL GENERATION
=======================================================
Total Customers : 5
Total Segments  : 5
Valid Emails    : 5

Segments:
- Champions
- Loyal Customers
- Potential Loyalists
- At Risk
- Lost Customers

Status: COMPLETED