<a href="https://colab.research.google.com/github/953625244013-cell/RFM-CLV-Personalized-Email/blob/main/developing_a_email_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

In [9]:
data = {
    'CustomerID': [
        101, 101, 101,
        102, 102,
        103, 103, 103, 103,
        104,
        105, 105, 105,
        106, 106,
        107, 107, 107,
        108,
        109, 109,
        110, 110, 110
    ],

    'CustomerName': [
        'Dharshini', 'Dharshini', 'Dharshini',
        'Priya', 'Priya',
        'Kavi', 'Kavi', 'Kavi', 'Kavi',
        'Nithya',
        'Dharnitha', 'Dharnitha', 'Dharnitha',
        'Selva', 'Selva',
        'Jeya', 'Jeya', 'Jeya',
        'Krishna',
        'Anu', 'Anu',
        'Divya', 'Divya', 'Divya'
    ],

    'InvoiceNo': [
        'INV001', 'INV002', 'INV003',
        'INV004', 'INV005',
        'INV006', 'INV007', 'INV008', 'INV009',
        'INV010',
        'INV011', 'INV012', 'INV013',
        'INV014', 'INV015',
        'INV016', 'INV017', 'INV018',
        'INV019',
        'INV020', 'INV021',
        'INV022', 'INV023', 'INV024'
    ],

    'InvoiceDate': [
        '2026-09-25', '2026-09-20', '2026-09-15',
        '2026-09-10', '2026-08-20',
        '2026-09-28', '2026-09-18', '2026-09-05', '2026-08-15',
        '2026-07-10',
        '2026-09-01', '2026-08-10', '2026-07-20',
        '2026-06-15', '2026-05-10',
        '2026-09-27', '2026-09-12', '2026-08-25',
        '2026-04-15',
        '2026-03-10', '2026-02-15',
        '2026-09-29', '2026-09-20', '2026-09-10'
    ],

    'Quantity': [
        2, 3, 1,
        2, 1,
        5, 3, 4, 2,
        1,
        2, 3, 2,
        1, 2,
        4, 3, 2,
        1,
        2, 1,
        3, 2, 4
    ],

    'UnitPrice': [
        500, 750, 1000,
        400, 600,
        200, 350, 250, 500,
        300,
        450, 300, 600,
        1000, 750,
        250, 400, 500,
        800,
        300, 500,
        200, 350, 450
    ]
}

df = pd.DataFrame(data)

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

print("Dataset created successfully!")
print("Number of transactions:", len(df))

df.head()

Dataset created successfully!
Number of transactions: 24

   CustomerID CustomerName InvoiceNo InvoiceDate  Quantity  UnitPrice
0         101    Dharshini    INV001  2026-09-25         2        500
1         101    Dharshini    INV002  2026-09-20         3        750
2         101    Dharshini    INV003  2026-09-15         1       1000
3         102        Priya    INV004  2026-09-10         2        400
4         102        Priya    INV005  2026-08-20         1        600

In [10]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset:")
display(df)

Rows: 24
Columns: 6

Column names:
['CustomerID', 'CustomerName', 'InvoiceNo', 'InvoiceDate', 'Quantity', 'UnitPrice']

Dataset:

    CustomerID CustomerName InvoiceNo InvoiceDate  Quantity  UnitPrice
0          101    Dharshini    INV001  2026-09-25         2        500
1          101    Dharshini    INV002  2026-09-20         3        750
2          101    Dharshini    INV003  2026-09-15         1       1000
3          102        Priya    INV004  2026-09-10         2        400
4          102        Priya    INV005  2026-08-20         1        600
5          103         Kavi    INV006  2026-09-28         5        200
6          103         Kavi    INV007  2026-09-18         3        350
7          103         Kavi    INV008  2026-09-05         4        250
8          103         Kavi    INV009  2026-08-15         2        500
9          104       Nithya    INV010  2026-07-10         1        300
10         105    Dharnitha    INV011  2026-09-01         2        450
11         105    Dharnitha    INV012  2026-08-10         3        300
12         105    Dharnitha    INV013  2026-07-20         2        600
13         106        Selva    INV014  2026-06-15         1       1000
14         106        Selva    INV015  2026-05-10         2        750
15         107         Jeya    INV016  2026-09-27         4        250
16         107         Jeya    INV017  2026-09-12         3        400
17         107         Jeya    INV018  2026-08-25         2        500
18         108      Krishna    INV019  2026-04-15         1        800
19         109          Anu    INV020  2026-03-10         2        300
20         109          Anu    INV021  2026-02-15         1        500
21         110        Divya    INV022  2026-09-29         3        200
22         110        Divya    INV023  2026-09-20         2        350
23         110        Divya    INV024  2026-09-10         4        450

In [12]:
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

display(df[
    ['CustomerID',
     'CustomerName',
     'Quantity',
     'UnitPrice',
     'TotalAmount']
])

    CustomerID CustomerName  Quantity  UnitPrice  TotalAmount
0          101    Dharshini         2        500         1000
1          101    Dharshini         3        750         2250
2          101    Dharshini         1       1000         1000
3          102        Priya         2        400          800
4          102        Priya         1        600          600
5          103         Kavi         5        200         1000
6          103         Kavi         3        350         1050
7          103         Kavi         4        250         1000
8          103         Kavi         2        500         1000
9          104       Nithya         1        300          300
10         105    Dharnitha         2        450          900
11         105    Dharnitha         3        300          900
12         105    Dharnitha         2        600         1200
13         106        Selva         1       1000         1000
14         106        Selva         2        750         1500
15         107         Jeya         4        250         1000
16         107         Jeya         3        400         1200
17         107         Jeya         2        500         1000
18         108      Krishna         1        800          800
19         109          Anu         2        300          600
20         109          Anu         1        500          500
21         110        Divya         3        200          600
22         110        Divya         2        350          700
23         110        Divya         4        450         1800

In [13]:
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

df[['Quantity', 'UnitPrice', 'TotalAmount']].head()

   Quantity  UnitPrice  TotalAmount
0         2        500         1000
1         3        750         2250
2         1       1000         1000
3         2        400          800
4         1        600          600

In [14]:
analysis_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

print("Analysis Date:", analysis_date)

Analysis Date: 2026-09-30 00:00:00

In [15]:
rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (analysis_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalAmount': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']

rfm.head()

            Recency  Frequency  Monetary
CustomerID
101               5          3      4250
102              20          2      1400
103               2          4      4050
104              82          1       300
105              29          3      3000

In [16]:
rfm = rfm[rfm['Monetary'] > 0]
rfm = rfm[rfm['Frequency'] > 0]

print("Customers after cleaning:", len(rfm))
rfm.head()

Customers after cleaning: 10

            Recency  Frequency  Monetary
CustomerID
101               5          3      4250
102              20          2      1400
103               2          4      4050
104              82          1       300
105              29          3      3000

In [18]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency'].rank(method='first'),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm.head()

            Recency  Frequency  Monetary  R_Score  F_Score  M_Score
CustomerID
101               5          3      4250        4        3        5
102              20          2      1400        3        2        2
103               2          4      4050        5        5        5
104              82          1       300        2        1        1
105              29          3      3000        3        4        3

In [20]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency'].rank(method='first'),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

print("RFM individual scores created!")

RFM individual scores created!

In [21]:
rfm['RFM_Score'] = (
    rfm['R_Score'] +
    rfm['F_Score'] +
    rfm['M_Score']
)

print("RFM Score created!")

rfm[
    ['Recency', 'Frequency', 'Monetary',
     'R_Score', 'F_Score', 'M_Score', 'RFM_Score']
].head()

RFM Score created!

            Recency  Frequency  Monetary  R_Score  F_Score  M_Score  RFM_Score
CustomerID
101               5          3      4250        4        3        5         12
102              20          2      1400        3        2        2          7
103               2          4      4050        5        5        5         15
104              82          1       300        2        1        1          4
105              29          3      3000        3        4        3         10

In [23]:
def get_segment(score):

    if score >= 13:
        return "Champions"

    elif score >= 11:
        return "Loyal Customers"

    elif score >= 9:
        return "Potential Loyalists"

    elif score >= 7:
        return "At Risk"

    elif score >= 5:
        return "Lost Customers"

    else:
        return "Others"


rfm['Segment'] = rfm['RFM_Score'].apply(get_segment)

print("Segment created successfully!")

rfm[['RFM_Score', 'Segment']].head()

Segment created successfully!

            RFM_Score              Segment
CustomerID
101                12      Loyal Customers
102                 7              At Risk
103                15            Champions
104                 4               Others
105                10  Potential Loyalists

In [24]:
rfm['AverageOrderValue'] = (
    rfm['Monetary'] / rfm['Frequency']
)

rfm['PurchaseFrequency'] = rfm['Frequency']

rfm['CLV'] = (
    rfm['AverageOrderValue'] *
    rfm['PurchaseFrequency']
)

rfm[['Monetary',
     'Frequency',
     'AverageOrderValue',
     'CLV']].head()

            Monetary  Frequency  AverageOrderValue     CLV
CustomerID
101             4250          3        1416.666667  4250.0
102             1400          2         700.000000  1400.0
103             4050          4        1012.500000  4050.0
104              300          1         300.000000   300.0
105             3000          3        1000.000000  3000.0

In [25]:
promotion = {
    "Champions": "20% discount",
    "Loyal Customers": "15% discount",
    "Potential Loyalists": "10% discount",
    "At Risk": "25% discount",
    "Lost Customers": "30% discount",
    "Others": "10% discount"
}

rfm['Promotion'] = rfm['Segment'].map(promotion)

rfm[['Segment', 'Promotion']].head()

                        Segment     Promotion
CustomerID
101             Loyal Customers  15% discount
102                     At Risk  25% discount
103                   Champions  20% discount
104                      Others  10% discount
105         Potential Loyalists  10% discount

In [26]:
promotion = {
    "Champions": "20% discount",
    "Loyal Customers": "15% discount",
    "Potential Loyalists": "10% discount",
    "At Risk": "25% discount",
    "Lost Customers": "30% discount",
    "Others": "10% discount"
}

rfm['Promotion'] = rfm['Segment'].map(promotion)

rfm[['Segment', 'Promotion']].head()

                        Segment     Promotion
CustomerID
101             Loyal Customers  15% discount
102                     At Risk  25% discount
103                   Champions  20% discount
104                      Others  10% discount
105         Potential Loyalists  10% discount

In [27]:
def generate_email(customer_name, segment, promotion, clv):

    if segment == "Champions":
        message = (
            "Thank you for being one of our most valuable customers! "
            "We truly appreciate your continued support."
        )

    elif segment == "Loyal Customers":
        message = (
            "We appreciate your continued loyalty and would love "
            "to make your next shopping experience even better."
        )

    elif segment == "Potential Loyalists":
        message = (
            "We noticed your recent interest in our products. "
            "We would love to see you shop with us again."
        )

    elif segment == "At Risk":
        message = (
            "We miss seeing you! Come back and enjoy a special "
            "offer created especially for you."
        )

    elif segment == "Lost Customers":
        message = (
            "We haven't seen you for a while and would love to "
            "welcome you back."
        )

    else:
        message = (
            "Thank you for shopping with us. "
            "We have a special offer for your next purchase."
        )

    email = f"""
Subject: A Special Offer Just for You, {customer_name}!

Hi {customer_name},

{message}

As a valued customer, you can enjoy an exclusive
{promotion} on your next purchase.

Your estimated customer lifetime value is ₹{clv:,.2f}.

Don't miss this opportunity!

Best regards,
Customer Success Team
"""

    return email

In [28]:
customer_names = df.groupby('CustomerID')['CustomerName'].first()

rfm['CustomerName'] = rfm.index.map(customer_names)

rfm[['CustomerName', 'Segment']].head()

           CustomerName              Segment
CustomerID
101           Dharshini      Loyal Customers
102               Priya              At Risk
103                Kavi            Champions
104              Nithya               Others
105           Dharnitha  Potential Loyalists

In [29]:
customer_names = df.groupby('CustomerID')['CustomerName'].first()

rfm['CustomerName'] = rfm.index.map(customer_names)

rfm[['CustomerName', 'Segment']].head()

           CustomerName              Segment
CustomerID
101           Dharshini      Loyal Customers
102               Priya              At Risk
103                Kavi            Champions
104              Nithya               Others
105           Dharnitha  Potential Loyalists

In [30]:
rfm['PersonalizedEmail'] = rfm.apply(
    lambda row: generate_email(
        row['CustomerName'],
        row['Segment'],
        row['Promotion'],
        row['CLV']
    ),
    axis=1
)

print("Personalized emails generated successfully!")

Personalized emails generated successfully!

In [32]:
print(rfm.iloc[0]['PersonalizedEmail'])

Subject: A Special Offer Just for You, Dharshini!

Hi Dharshini,

We appreciate your continued loyalty and would love to make your next shopping experience even better.

As a valued customer, you can enjoy an exclusive
15% discount on your next purchase.

Your estimated customer lifetime value is ₹4,250.00.

Don't miss this opportunity!

Best regards,
Customer Success Team

In [31]:
output = rfm[
    [
        'CustomerName',
        'Recency',
        'Frequency',
        'Monetary',
        'RFM_Score',
        'Segment',
        'CLV',
        'Promotion',
        'PersonalizedEmail'
    ]
]

output.head()

,CustomerName,Recency,Frequency,Monetary,RFM_Score,Segment,CLV,Promotion,PersonalizedEmail
CustomerID,,,,,,,,,
101,Dharshini,5,3,4250,12,Loyal Customers,4250.0,15% discount,"\nSubject: A Special Offer Just for You, Dhars..."
102,Priya,20,2,1400,7,At Risk,1400.0,25% discount,"\nSubject: A Special Offer Just for You, Priya..."
103,Kavi,2,4,4050,15,Champions,4050.0,20% discount,"\nSubject: A Special Offer Just for You, Kavi!..."
104,Nithya,82,1,300,4,Others,300.0,10% discount,"\nSubject: A Special Offer Just for You, Nithy..."
105,Dharnitha,29,3,3000,10,Potential Loyalists,3000.0,10% discount,"\nSubject: A Special Offer Just for You, Dharn..."

In [33]:
output.to_csv(
    'personalized_customer_emails.csv',
    index=False
)

print("File saved successfully!")

File saved successfully!

In [35]:
from google.colab import files

files.download('personalized_customer_emails.csv')

In [36]:
output.to_csv(
    'personalized_customer_emails.csv',
    index=False
)

print("File saved successfully!")

File saved successfully!

In [37]:
from google.colab import files

files.download('personalized_customer_emails.csv')