<a href="https://colab.research.google.com/github/953625244013-cell/RFM-CLV-Personalized-Email/blob/main/Test_Email_Generation_for_Different_Customer_Segmentsday_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Cell 1: Test Customers from Different Segments

test_customers = [
    {"name": "Arun", "segment": "Champions"},
    {"name": "Priya", "segment": "Loyal Customers"},
    {"name": "Kavi", "segment": "Potential Loyalists"},
    {"name": "Dharshini", "segment": "At Risk"},
    {"name": "Rahul", "segment": "Lost Customers"},
    {"name": "Nithya", "segment": "Others"}
]

print("Testing email generation for different customer segments:")
print(f"Total customers to test: {len(test_customers)}")

for customer in test_customers:
    print(customer)

Testing email generation for different customer segments:
Total customers to test: 6
{'name': 'Arun', 'segment': 'Champions'}
{'name': 'Priya', 'segment': 'Loyal Customers'}
{'name': 'Kavi', 'segment': 'Potential Loyalists'}
{'name': 'Dharshini', 'segment': 'At Risk'}
{'name': 'Rahul', 'segment': 'Lost Customers'}
{'name': 'Nithya', 'segment': 'Others'}

In [2]:
# Cell 2: Segment-Specific Promotions

promotions = {
    "Champions": "20% exclusive discount",
    "Loyal Customers": "15% loyalty discount",
    "Potential Loyalists": "10% special discount",
    "At Risk": "25% win-back discount",
    "Lost Customers": "30% re-engagement discount",
    "Others": "10% special offer"
}

for segment, offer in promotions.items():
    print(f"{segment}: {offer}")

Champions: 20% exclusive discount
Loyal Customers: 15% loyalty discount
Potential Loyalists: 10% special discount
At Risk: 25% win-back discount
Lost Customers: 30% re-engagement discount
Others: 10% special offer

In [3]:
# Cell 3: Create Segment-Specific Prompts

def create_prompt(customer_name, segment, promotion):
    prompt = f"""
Create a personalized promotional email for the customer.

Customer Name: {customer_name}
Customer Segment: {segment}
Promotion: {promotion}

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>
"""
    return prompt


# Test prompt creation
for customer in test_customers:
    name = customer["name"]
    segment = customer["segment"]
    promotion = promotions[segment]

    prompt = create_prompt(name, segment, promotion)

    print("=" * 70)
    print(prompt)

======================================================================

Create a personalized promotional email for the customer.

Customer Name: Arun
Customer Segment: Champions
Promotion: 20% exclusive discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>

======================================================================

Create a personalized promotional email for the customer.

Customer Name: Priya
Customer Segment: Loyal Customers
Promotion: 15% loyalty discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>

======================================================================

Create a personalized promotional email for the customer.

Customer Name: Kavi
Customer Segment: Potential Loyalists
Promotion: 10% special discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>

======================================================================

Create a personalized promotional email for the customer.

Customer Name: Dharshini
Customer Segment: At Risk
Promotion: 25% win-back discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>

======================================================================

Create a personalized promotional email for the customer.

Customer Name: Rahul
Customer Segment: Lost Customers
Promotion: 30% re-engagement discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>

======================================================================

Create a personalized promotional email for the customer.

Customer Name: Nithya
Customer Segment: Others
Promotion: 10% special offer

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>

In [6]:
# Cell 4: Generate Email Prompts for Testing

generated_emails = []

for customer in test_customers:
    name = customer["name"]
    segment = customer["segment"]
    promotion = promotions[segment]

    prompt = create_prompt(
        customer_name=name,
        segment=segment,
        promotion=promotion
    )

    generated_emails.append({
        "customer": name,
        "segment": segment,
        "promotion": promotion,
        "prompt": prompt
    })

print("Prompts created successfully!")
print("Total prompts:", len(generated_emails))

Prompts created successfully!
Total prompts: 6

In [8]:
# Cell 5: Display Test Prompts

for item in generated_emails:

    print("=" * 70)
    print("CUSTOMER :", item["customer"])
    print("SEGMENT  :", item["segment"])
    print("PROMOTION:", item["promotion"])
    print("-" * 70)
    print(item["prompt"])
    print()

======================================================================
CUSTOMER : Arun
SEGMENT  : Champions
PROMOTION: 20% exclusive discount
----------------------------------------------------------------------

Create a personalized promotional email for the customer.

Customer Name: Arun
Customer Segment: Champions
Promotion: 20% exclusive discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>


======================================================================
CUSTOMER : Priya
SEGMENT  : Loyal Customers
PROMOTION: 15% loyalty discount
----------------------------------------------------------------------

Create a personalized promotional email for the customer.

Customer Name: Priya
Customer Segment: Loyal Customers
Promotion: 15% loyalty discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>


======================================================================
CUSTOMER : Kavi
SEGMENT  : Potential Loyalists
PROMOTION: 10% special discount
----------------------------------------------------------------------

Create a personalized promotional email for the customer.

Customer Name: Kavi
Customer Segment: Potential Loyalists
Promotion: 10% special discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>


======================================================================
CUSTOMER : Dharshini
SEGMENT  : At Risk
PROMOTION: 25% win-back discount
----------------------------------------------------------------------

Create a personalized promotional email for the customer.

Customer Name: Dharshini
Customer Segment: At Risk
Promotion: 25% win-back discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>


======================================================================
CUSTOMER : Rahul
SEGMENT  : Lost Customers
PROMOTION: 30% re-engagement discount
----------------------------------------------------------------------

Create a personalized promotional email for the customer.

Customer Name: Rahul
Customer Segment: Lost Customers
Promotion: 30% re-engagement discount

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>


======================================================================
CUSTOMER : Nithya
SEGMENT  : Others
PROMOTION: 10% special offer
----------------------------------------------------------------------

Create a personalized promotional email for the customer.

Customer Name: Nithya
Customer Segment: Others
Promotion: 10% special offer

Requirements:
- Use the customer's name.
- Make the email relevant to the customer segment.
- Clearly mention the promotion.
- Keep the email friendly and professional.
- Include a subject line.
- Keep the email concise.

Return the result as:
Subject: <subject>
Email: <email body>

In [9]:
# Cell 6: Verify All Customer Segments

print("CUSTOMER SEGMENT TEST")
print("=" * 70)

for item in generated_emails:
    print(f"Customer  : {item['customer']}")
    print(f"Segment   : {item['segment']}")
    print(f"Promotion : {item['promotion']}")
    print("-" * 70)

print("\nTotal customers tested:", len(generated_emails))
print("Total segments tested:", len(set(item["segment"] for item in generated_emails)))

CUSTOMER SEGMENT TEST
======================================================================
Customer  : Arun
Segment   : Champions
Promotion : 20% exclusive discount
----------------------------------------------------------------------
Customer  : Priya
Segment   : Loyal Customers
Promotion : 15% loyalty discount
----------------------------------------------------------------------
Customer  : Kavi
Segment   : Potential Loyalists
Promotion : 10% special discount
----------------------------------------------------------------------
Customer  : Dharshini
Segment   : At Risk
Promotion : 25% win-back discount
----------------------------------------------------------------------
Customer  : Rahul
Segment   : Lost Customers
Promotion : 30% re-engagement discount
----------------------------------------------------------------------
Customer  : Nithya
Segment   : Others
Promotion : 10% special offer
----------------------------------------------------------------------

Total customers tested: 6
Total segments tested: 6

In [10]:
# Cell 7: Generate Segment-Specific Email Templates

def generate_test_email(customer_name, segment, promotion):

    messages = {
        "Champions":
            "Thank you for being one of our most valued customers!",

        "Loyal Customers":
            "We truly appreciate your continued loyalty and support!",

        "Potential Loyalists":
            "We would love to see you shop with us again!",

        "At Risk":
            "We miss you! Come back and enjoy this special offer.",

        "Lost Customers":
            "We would love to welcome you back with a special offer!",

        "Others":
            "Enjoy this special offer on your next purchase!"
    }

    message = messages.get(
        segment,
        "Thank you for being our valued customer!"
    )

    email = f"""
Subject: Special Offer Just for You!

Hi {customer_name},

{message}

As a {segment} customer, you can enjoy
{promotion} on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team
"""

    return email


for customer in test_customers:

    name = customer["name"]
    segment = customer["segment"]
    promotion = promotions[segment]

    email = generate_test_email(
        name,
        segment,
        promotion
    )

    print("=" * 70)
    print("CUSTOMER:", name)
    print("SEGMENT :", segment)
    print(email)

======================================================================
CUSTOMER: Arun
SEGMENT : Champions

Subject: Special Offer Just for You!

Hi Arun,

Thank you for being one of our most valued customers!

As a Champions customer, you can enjoy
20% exclusive discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team

======================================================================
CUSTOMER: Priya
SEGMENT : Loyal Customers

Subject: Special Offer Just for You!

Hi Priya,

We truly appreciate your continued loyalty and support!

As a Loyal Customers customer, you can enjoy
15% loyalty discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team

======================================================================
CUSTOMER: Kavi
SEGMENT : Potential Loyalists

Subject: Special Offer Just for You!

Hi Kavi,

We would love to see you shop with us again!

As a Potential Loyalists customer, you can enjoy
10% special discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team

======================================================================
CUSTOMER: Dharshini
SEGMENT : At Risk

Subject: Special Offer Just for You!

Hi Dharshini,

We miss you! Come back and enjoy this special offer.

As a At Risk customer, you can enjoy
25% win-back discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team

======================================================================
CUSTOMER: Rahul
SEGMENT : Lost Customers

Subject: Special Offer Just for You!

Hi Rahul,

We would love to welcome you back with a special offer!

As a Lost Customers customer, you can enjoy
30% re-engagement discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team

======================================================================
CUSTOMER: Nithya
SEGMENT : Others

Subject: Special Offer Just for You!

Hi Nithya,

Enjoy this special offer on your next purchase!

As a Others customer, you can enjoy
10% special offer on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team

In [11]:
# Cell 8: Store Generated Emails

import pandas as pd

test_results = []

for customer in test_customers:

    name = customer["name"]
    segment = customer["segment"]
    promotion = promotions[segment]

    email = generate_test_email(
        name,
        segment,
        promotion
    )

    test_results.append({
        "Customer": name,
        "Segment": segment,
        "Promotion": promotion,
        "Generated_Email": email
    })

results_df = pd.DataFrame(test_results)

print("Email generation test completed!")
print("Total emails:", len(results_df))

results_df

Email generation test completed!
Total emails: 6

,Customer,Segment,Promotion,Generated_Email
0,Arun,Champions,20% exclusive discount,\nSubject: Special Offer Just for You!\n\nHi A...
1,Priya,Loyal Customers,15% loyalty discount,\nSubject: Special Offer Just for You!\n\nHi P...
2,Kavi,Potential Loyalists,10% special discount,\nSubject: Special Offer Just for You!\n\nHi K...
3,Dharshini,At Risk,25% win-back discount,\nSubject: Special Offer Just for You!\n\nHi D...
4,Rahul,Lost Customers,30% re-engagement discount,\nSubject: Special Offer Just for You!\n\nHi R...
5,Nithya,Others,10% special offer,\nSubject: Special Offer Just for You!\n\nHi N...

In [12]:
# Cell 9: Validate Email Generation

print("EMAIL GENERATION VALIDATION")
print("=" * 60)

for index, row in results_df.iterrows():

    if pd.notna(row["Generated_Email"]) and row["Generated_Email"].strip() != "":
        status = "SUCCESS"
    else:
        status = "FAILED"

    print(f"Customer : {row['Customer']}")
    print(f"Segment  : {row['Segment']}")
    print(f"Status   : {status}")
    print("-" * 60)

successful = results_df["Generated_Email"].notna().sum()

print("\nTotal emails generated :", len(results_df))
print("Successful emails      :", successful)
print("Failed emails          :", len(results_df) - successful)

EMAIL GENERATION VALIDATION
============================================================
Customer : Arun
Segment  : Champions
Status   : SUCCESS
------------------------------------------------------------
Customer : Priya
Segment  : Loyal Customers
Status   : SUCCESS
------------------------------------------------------------
Customer : Kavi
Segment  : Potential Loyalists
Status   : SUCCESS
------------------------------------------------------------
Customer : Dharshini
Segment  : At Risk
Status   : SUCCESS
------------------------------------------------------------
Customer : Rahul
Segment  : Lost Customers
Status   : SUCCESS
------------------------------------------------------------
Customer : Nithya
Segment  : Others
Status   : SUCCESS
------------------------------------------------------------

Total emails generated : 6
Successful emails      : 6
Failed emails          : 0

In [13]:
# Cell 10: Display Final Personalized Emails

for index, row in results_df.iterrows():

    print("\n" + "=" * 80)
    print(f"CUSTOMER : {row['Customer']}")
    print(f"SEGMENT  : {row['Segment']}")
    print(f"PROMOTION: {row['Promotion']}")
    print("=" * 80)

    print(row["Generated_Email"])

================================================================================
CUSTOMER : Arun
SEGMENT  : Champions
PROMOTION: 20% exclusive discount
================================================================================

Subject: Special Offer Just for You!

Hi Arun,

Thank you for being one of our most valued customers!

As a Champions customer, you can enjoy
20% exclusive discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team


================================================================================
CUSTOMER : Priya
SEGMENT  : Loyal Customers
PROMOTION: 15% loyalty discount
================================================================================

Subject: Special Offer Just for You!

Hi Priya,

We truly appreciate your continued loyalty and support!

As a Loyal Customers customer, you can enjoy
15% loyalty discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team


================================================================================
CUSTOMER : Kavi
SEGMENT  : Potential Loyalists
PROMOTION: 10% special discount
================================================================================

Subject: Special Offer Just for You!

Hi Kavi,

We would love to see you shop with us again!

As a Potential Loyalists customer, you can enjoy
10% special discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team


================================================================================
CUSTOMER : Dharshini
SEGMENT  : At Risk
PROMOTION: 25% win-back discount
================================================================================

Subject: Special Offer Just for You!

Hi Dharshini,

We miss you! Come back and enjoy this special offer.

As a At Risk customer, you can enjoy
25% win-back discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team


================================================================================
CUSTOMER : Rahul
SEGMENT  : Lost Customers
PROMOTION: 30% re-engagement discount
================================================================================

Subject: Special Offer Just for You!

Hi Rahul,

We would love to welcome you back with a special offer!

As a Lost Customers customer, you can enjoy
30% re-engagement discount on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team


================================================================================
CUSTOMER : Nithya
SEGMENT  : Others
PROMOTION: 10% special offer
================================================================================

Subject: Special Offer Just for You!

Hi Nithya,

Enjoy this special offer on your next purchase!

As a Others customer, you can enjoy
10% special offer on your next purchase.

Don't miss this special opportunity!

Best regards,
Customer Team

In [14]:
# Cell 11: Export Email Test Results

output_file = "customer_segment_email_test_results.csv"

results_df.to_csv(output_file, index=False)

print("Test results saved successfully!")
print("File:", output_file)

Test results saved successfully!
File: customer_segment_email_test_results.csv

In [15]:
# Cell 12: Download Test Results

from google.colab import files

files.download("customer_segment_email_test_results.csv")

print("Download started!")

Download started!

In [16]:
# Cell 13: Segment-wise Email Generation Summary

segment_summary = (
    results_df
    .groupby("Segment")
    .size()
    .reset_index(name="Email_Count")
)

print("SEGMENT-WISE EMAIL GENERATION SUMMARY")
print("=" * 60)

print(segment_summary.to_string(index=False))

print("\nTotal emails generated:", segment_summary["Email_Count"].sum())

SEGMENT-WISE EMAIL GENERATION SUMMARY
============================================================
            Segment  Email_Count
            At Risk            1
          Champions            1
     Lost Customers            1
    Loyal Customers            1
             Others            1
Potential Loyalists            1

Total emails generated: 6

In [17]:
# Cell 14: Check Email Personalization

print("PERSONALIZATION CHECK")
print("=" * 70)

for index, row in results_df.iterrows():

    email = row["Generated_Email"]

    name_check = row["Customer"] in email
    segment_check = row["Segment"] in email
    promotion_check = row["Promotion"] in email

    if name_check and segment_check and promotion_check:
        status = "PASS"
    else:
        status = "CHECK"

    print(f"Customer : {row['Customer']}")
    print(f"Segment  : {row['Segment']}")
    print(f"Name     : {'YES' if name_check else 'NO'}")
    print(f"Segment  : {'YES' if segment_check else 'NO'}")
    print(f"Promotion: {'YES' if promotion_check else 'NO'}")
    print(f"Status   : {status}")
    print("-" * 70)

PERSONALIZATION CHECK
======================================================================
Customer : Arun
Segment  : Champions
Name     : YES
Segment  : YES
Promotion: YES
Status   : PASS
----------------------------------------------------------------------
Customer : Priya
Segment  : Loyal Customers
Name     : YES
Segment  : YES
Promotion: YES
Status   : PASS
----------------------------------------------------------------------
Customer : Kavi
Segment  : Potential Loyalists
Name     : YES
Segment  : YES
Promotion: YES
Status   : PASS
----------------------------------------------------------------------
Customer : Dharshini
Segment  : At Risk
Name     : YES
Segment  : YES
Promotion: YES
Status   : PASS
----------------------------------------------------------------------
Customer : Rahul
Segment  : Lost Customers
Name     : YES
Segment  : YES
Promotion: YES
Status   : PASS
----------------------------------------------------------------------
Customer : Nithya
Segment  : Others
Name     : YES
Segment  : YES
Promotion: YES
Status   : PASS
----------------------------------------------------------------------

In [18]:
# Cell 15: Final Email Generation Test Report

total_customers = len(results_df)

successful_emails = 0

for index, row in results_df.iterrows():
    email = row["Generated_Email"]

    if (
        row["Customer"] in email
        and row["Segment"] in email
        and row["Promotion"] in email
    ):
        successful_emails += 1

failed_emails = total_customers - successful_emails

print("=" * 70)
print("FINAL EMAIL GENERATION TEST REPORT")
print("=" * 70)

print("Total Customers Tested :", total_customers)
print("Successful Emails      :", successful_emails)
print("Failed Emails          :", failed_emails)

if failed_emails == 0:
    print("\nRESULT: ALL EMAIL GENERATION TESTS PASSED")
else:
    print("\nRESULT: SOME EMAIL TESTS NEED REVIEW")

======================================================================
FINAL EMAIL GENERATION TEST REPORT
======================================================================
Total Customers Tested : 6
Successful Emails      : 6
Failed Emails          : 0

RESULT: ALL EMAIL GENERATION TESTS PASSED

In [19]:
# Cell 16: Save Final Test Report

final_report = pd.DataFrame({
    "Metric": [
        "Total Customers Tested",
        "Successful Emails",
        "Failed Emails",
        "Segments Tested"
    ],
    "Value": [
        total_customers,
        successful_emails,
        failed_emails,
        results_df["Segment"].nunique()
    ]
})

final_report.to_csv(
    "email_generation_final_report.csv",
    index=False
)

print("Final test report saved successfully!")
print("\n")
print(final_report)

Final test report saved successfully!


                   Metric  Value
0  Total Customers Tested      6
1       Successful Emails      6
2           Failed Emails      0
3         Segments Tested      6

In [20]:
# Cell 17: Download Final Test Report

from google.colab import files

files.download("email_generation_final_report.csv")

print("Final report download started!")

Final report download started!

In [22]:
# Cell 18: Check Available Data

print("Checking available data...")

print("\nRFM variable exists:", "rfm" in globals())

if "rfm" in globals():
    print("\nRFM columns:")
    print(rfm.columns.tolist())

    print("\nFirst 5 rows:")
    display(rfm.head())
else:
    print("\n'rfm' dataframe was not found.")
    print("Please check the dataframe created in your earlier cells.")

Checking available data...

RFM variable exists: False

'rfm' dataframe was not found.
Please check the dataframe created in your earlier cells.

In [24]:
# Cell 19: Check All Variables

print("Variables available in notebook:")
print(list(globals().keys()))

Variables available in notebook:
['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', '_', '__', '___', '_i', '_ii', '_iii', '_i1', 'test_customers', 'customer', '_i2', 'promotions', 'segment', 'offer', '_i3', 'create_prompt', 'name', 'promotion', 'prompt', '_i4', 'generated_emails', '_i5', '_i6', '_i7', 'item', '_i8', '_i9', '_i10', 'generate_test_email', 'email', '_i11', 'pd', 'test_results', 'results_df', '_11', '_i12', 'index', 'row', 'status', 'successful', '_i13', '_i14', 'output_file', '_i15', 'files', '_i16', 'segment_summary', '_i17', 'name_check', 'segment_check', 'promotion_check', '_i18', 'total_customers', 'successful_emails', 'failed_emails', '_i19', 'final_report', '_i20', '_i21', '_i22', '_i23', '_i24']

In [26]:
print("Hello")

Hello

In [27]:
# Cell 21: Create Test Data

import pandas as pd

test_data = pd.DataFrame({
    "Customer": ["Arun", "Priya", "Kavi", "Dharshini", "Rahul", "Nithya"],
    "Segment": [
        "Champions",
        "Loyal Customers",
        "Potential Loyalists",
        "At Risk",
        "Lost Customers",
        "Others"
    ]
})

print("Test data created successfully!")
display(test_data)

Test data created successfully!

    Customer              Segment
0       Arun            Champions
1      Priya      Loyal Customers
2       Kavi  Potential Loyalists
3  Dharshini              At Risk
4      Rahul       Lost Customers
5     Nithya               Others